### ISSUE TITLE
UnauthorizedAccessException on TearDown

### ISSUE THREAD

**Issue by italodirenzo93** [MattHoneycutt/SpecsFor#108]
This code...
```c#
using NUnit.Framework;
using SpecsFor.Mvc;
using SpecsTest;

namespace NUnitTests
{
    [SetUpFixture]
    public class AssemblyStartup
    {
        private SpecsForIntegrationHost _host;

        [OneTimeSetUp]
        public void SetupTestRun()
        {
            var config = new SpecsForMvcConfig();
            config.UseIISExpress()
                .With(Project.Named("SpecsTest"))
                .ApplyWebConfigTransformForConfig("Debug");

            config.BuildRoutesUsing(r => RouteConfig.RegisterRoutes(r));
            config.UseBrowser(BrowserDriver.Chrome);
            config.SetBrowserWindowSize(1024, 768);

            _host = new SpecsForIntegrationHost(config);
            _host.Start();
        }

        [OneTimeTearDown]
        public void TearDownTestRun()
        {
            _host.Shutdown();
        }
    }
}
```
...produces this error when trying to run any test. 
```
TearDown failed for test fixture NUnitTests.AssemblyStartup
System.UnauthorizedAccessException : Access to the path 'C:\$WINDOWS.~BT\NewOS\ProgramData\Microsoft\Windows\SystemData' is denied.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at SpecsFor.Mvc.Project.DiscoverProject(String projectName, String currentFolder)
   at SpecsFor.Mvc.Project.Named(String projectName)
   at NUnitTests.AssemblyStartup.SetupTestRun() in C:\Sandbox\SpecsTest\NUnitTests\AssemblyStartup.cs:line 16
--TearDown
   at NUnitTests.AssemblyStartup.TearDownTestRun() in C:\Sandbox\SpecsTest\NUnitTests\AssemblyStartup.cs:line 31
NUnit Adapter 3.9.0.0: Test execution complete
========== Run test finished: 1 run (0:00:10.0701029) ==========
```

**Comment by MattHoneycutt** [comment]
The error is actually happening in SetupTestRun.  SpecsFor.Mvc is unable to find your project because it is attempting to enumerate a directory it doesn't have access to.  It could be a lot of different things causing that, including the test runner shadow-copying assemblies.  Instead, you may need to explicitly set the path to your test project:

```
 config.UseIISExpress()
                .With("/path/to/your/project.csproj")
                .ApplyWebConfigTransformForConfig("Debug");
```

**Comment by italodirenzo93** [comment]
Thanks. I will give that a shot.
