### ISSUE TITLE
Creating strongly typed FakeHtmlHelper throws null reference exception.

### ISSUE THREAD

**Issue by robertsimmons** [MattHoneycutt/SpecsFor#75]
Using: new FakeHtmlHelper<DummyModel>(null)

Gave a stack trace of:

at SpecsFor.Helpers.Web.Mvc.FakeHttpContext..ctor(IPrincipal principal, IFormParamsProvider formParams, IQueryStringParamsProvider queryStringParams, ICookieProvider cookies, SessionStateItemCollection sessionItems, HttpServerUtilityBase server, FakeHttpRequest request, IHttpContextBehavior contextBehavior)
   at SpecsFor.Helpers.Web.Mvc.FakeHtmlHelper`1..ctor(TModel model, FakeViewContext viewContext)

**Comment by MattHoneycutt** [comment]
Fixed in latest release, which will go out later today.  Yay for the ?. operator!
